### ISSUE TITLE
Attester loops with "Failed to verify EK certificate: no issuer certificate found'

### ISSUE THREAD

**Issue by pietrushnic** [fobnail/fobnail-attester#24]
I'm trying to follow instructions from [blog post](https://blog.3mdeb.com/2022/2022-03-21-fobnail_3rd_phase/), after running `./docker.sh run-tmux` I'm getting from client:

```shell
 INFO  fobnail::client        > Received EK certificate
 INFO  fobnail::client        > X.509 version 3
 WARN  fobnail::certmgr::x509 > Unknown OID 2.5.4.3
 INFO  fobnail::client        > Issuer: C = PL, ST = State, O = Fobnail
 WARN  fobnail::certmgr::x509 > Unknown OID 2.5.4.3
 INFO  fobnail::client        > Subject: C = PL, ST = State, O = Fobnail
 INFO  fobnail::client        > Key: RSA2048
 WARN  fobnail::certmgr::x509 > Unknown OID 2.5.4.3
 ERROR fobnail::client        > Failed to verify EK certificate: no issuer certificate found
```

And from attester:

```shell
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f2ac3bf9520 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:440:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpm0: No such file or directory
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f2ac3bf9520 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-device
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:223:tcti_control_command() Control command failed with error: 0
ERROR:tcti:src/tss2-tcti/tcti-swtpm.c:331:tcti_swtpm_set_locality() Failed to set locality: 0xa000a
WARNING:tcti:src/tss2-tcti/tcti-swtpm.c:600:Tss2_Tcti_Swtpm_Init() Could not set locality via control channel: 0xa000a
WARNING:tcti:src/tss2-tcti/tctildr.c:79:tcti_from_init() TCTI init for function 0x7f2ac3bf98d0 failed with a000a
WARNING:tcti:src/tss2-tcti/tctildr.c:109:tcti_from_info() Could not initialize TCTI named: tcti-swtpm
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-swtpm.so.0
AIK not found, generating one now. This may take a while...
Creating CoAP server endpoint using UDP.
Registering CoAP resources.
Entering main loop.
Received message: attest
Received message: ek
Received message: attest
Received message: attest
Received message: attest
Received message: attest
```

This seem to be infinite loop.

**Comment by krystian-hebel** [comment]
Title of this issue is misleading. Attester doesn't print this line, Verifier does.

This is most likely caused by https://github.com/fobnail/fobnail/issues/12

**Comment by pietrushnic** [comment]
Unfortunately it is not clear from blog post and also there is no information in logs what is what. At least nothing I can understand. It would be great if whole description and results we see would be explained and more user friendly. Of course if we want to have community support.

I believe you should have rights to mark issue as duplicate if you are sure this is the reason as well as changing issue title if it is misleading.

**Comment by arturkow2000** [comment]
The problem here is that Fobnail can't find root CA which we use for signing EK certificate. As Krystian pointed most likely caused by LittleFS corruption. If LittleFS is corrupted, Fobnail can't mount it and then it formats it and this is the result.
Other causes are unlikely.

**Comment by macpijan** [comment]
The issue with LFS will be tracked here: https://github.com/fobnail/fobnail/issues/12

We can keep this issue until we improve log readability - maybe add some banner at the start of each application, to inform which one is attester, which one is verified?

**Comment by macpijan** [comment]
@pietrushnic Can you try more (few more?) times as suggested here: https://github.com/fobnail/fobnail/issues/12#issuecomment-1080688658

It would mean you were lucky enough to trigger this bug. If not, it may be a different issue then.

**Comment by pietrushnic** [comment]
@macpijan I run container twice before I reported the issue, but I'm not sure what really retry mean, is it wiping everything from disk, building again or just rerunning. I will do that again and will get back here.

**Comment by pietrushnic** [comment]
@macpijan I tried 5+ times I'm getting 2 signatures of the problem. First is this mentioned above `Failed to verify EK certificate: no issuer certificate found`. Second is as in following asciinema `WARN: Cannot find any physical network interface in sysfs`:

[![asciicast](https://asciinema.org/a/tOT3sa1lLu3o4PzSSxd0bUf3m.svg)](https://asciinema.org/a/tOT3sa1lLu3o4PzSSxd0bUf3m)

In summary, I cannot test Fobnail code developed so far.

**Comment by krystian-hebel** [comment]
@pietrushnic can we close this issue given that Fobnail evolved from that point?

**Comment by pietrushnic** [comment]
@krystian-hebel, yes, it is no longer reproducible.
