### ISSUE TITLE
Attestation succeeds only for the first time

### ISSUE THREAD

**Issue by arturkow2000** [fobnail/fobnail-attester#26]
Further attestation attempts fail due to `libcoap` caching responses - when attesting for the first time (during lifetime of `fobnail-attester` process) Fobnail reads RIMs (which also act as evidence), to protect against replay attacks each evidence request has nonce which is used for computing evidence signature. Due to response caching `fobnail-attester` responds with an old signature..
Because of that
- if Fobnail reaches to a point where it reads RIMs then
- further attempts of attestation will fail, `fobnail-attester` either has to be restarted or user has to wait a few minutes so `libcoap` drops old response
- first attestation after provisioning also fails (during provisioning Fobnail reads RIMs)

With `coap-client` this problem looks differently - `fobnail-attester` still caches old responses, but to a new request with different nonce a response is generated. Over time old responses accumulate (dropped after a few minutes). It is unknown whether this may cause resource exhaustion, there may be some internal mechanism to prevent that.

We also use nonces for metadata, however metadata is not affected due to its small size (`libcoap` doesn't cache small responses).

**Comment by krystian-hebel** [comment]
@arturkow2000 this should no longer apply since Attester is now CoAP client. Can we close this issue?

**Comment by arturkow2000** [comment]
Yes, the problem is long gone, closing ...
